apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tensor-talks.fullname" . }}-jwt
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "tensor-talks.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.services.auth-service.jwt.secret | quote }}
  issuer: {{ .Values.services.auth-service.jwt.issuer | quote }}
  audience: {{ .Values.services.auth-service.jwt.audience | quote }}

